import React, { useState } from "react";

// {label : autogenerated, color: colorPattern, id: }

const CircleManagement = () => {
  const colors = ["blue", "pink", "yellow", "green"];
  const [circleData, setCircleData] = useState([]);
  const [selectedCircle, setSelectCircle] = useState(new Set());

  const handleClick = () => {
    let newData;
    if (circleData.length === 0) {
      newData = {
        count: 0,
        color: colors[0],
        label: 1,
      };
    } else {
      const lastItem = circleData[circleData.length - 1];
      const lastColorIndex = colors.findIndex(
        (item) => item === lastItem.color
      );
      const newIndex = lastColorIndex < 3 ? lastColorIndex + 1 : 0;
      newData = {
        count: 0,
        color: colors[newIndex],
        label: lastItem.label + 1,
      };
    }
    setCircleData([...circleData, newData]);
  };

  const handleDelete = () => {
    setCircleData((prev) => {
      return prev.filter((item) => !selectedCircle.has(item.label));
    });
    setSelectCircle(new Set());
  };

  const handleCircleClick = (event) => (label) => {
    if (event.shiftKey) {
      setSelectCircle((prev) => {
        const newSet = new Set(prev);
        if (newSet.has(label)) {
          newSet.delete(label);
        } else {
          newSet.add(label);
        }
        return newSet;
      });
    } else {
      setCircleData((prev) => {
        return prev?.map((item) => {
          if (item.label === label) {
            item.count = item.count + 1;
          }
          return item;
        });
      });
    }
  };

  return (
    <div className="circle-container">
      <div className="circle-header">
        <button onClick={handleClick}>Add</button>
        <button onClick={handleDelete}>Remove Selected</button>
      </div>
      <div className="circle-body">
        {circleData.map((circleItem, index) => {
          const color = circleItem.color;
          return (
            <div
              key={index}
              className={`circle ${color} ${
                selectedCircle.has(circleItem.label) ? "selected" : ""
              }`}
              onClick={(e) => handleCircleClick(e)(circleItem.label)}
            >
              {circleItem.label}&nbsp; count : {circleItem.count}
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default CircleManagement;
